### PR TITLE
Create ggslopegraph2

### PR DESCRIPTION
**Pull request by ibecav**
Here you go

### CODE REVIEW

**Comment by leeper** [comment]
I've merged this into https://github.com/leeper/slopegraph/tree/pr-26 with some stylistic edits to keep things consistent with the rest of the package (e.g., lowercase function arguments). That branch also included the changes from #27. 

@JustinMShea If you want to take a look, this could be a good first contribution making sure this all works and fits your vision for the package.

**Comment by ibecav** [comment]
Thanks!  Can I have commit privileges to pr-26?  I have a bunch of updates, post your changes.

**Comment by ibecav** [comment]
I think it's ready for merge!

**Comment by ibecav** [comment]
Hi just checking back.  These seems to have gone fallow?

**Comment by JustinMShea** [comment]
Yes, thanks for your diligence Chuck. Regretfully my circumstances for taking on this project have changed dramatically as of late. I think the good work of @ibecav  makes him the best candidate for taking it over at this time! Do you agree @leeper ?

**Comment by leeper** [comment]
@justinmshea, thanks for letting me know.  @ibecav if you're interested and believe you can support this long-term, please let me know.

**Comment by ibecav** [comment]
Thanks @JustinMShea Justin and Thomas @leeper so if support means keeping it basically maintained and answering the odd feature request and bug report sure as long as I can have the appropriate read write privileges.

It's actually CRAN ready to include a vignette I wrote I would just prefer to merge into your GitHub since for me it's a one off.

**Comment by leeper** [comment]
Ok. My inclination then is to give you edit rights here so you can merge these changes in and then we can see about maintainership. I don't have time to maintain but I'd like to make sure you're on board for this beyond the current contributions.

**Comment by ibecav** [comment]
Right for the ggslopegraph portions I'm in for the long haul. tbh no desire
to pick up any of the base plotting stuff though

**Comment by JustinMShea** [comment]
Hmmm....no desire to pickup the elegant and lightweight base? That was a
top priority for me.
Well shoot, perhaps I should stay on and see what my schedule can bring in
another month or so.

**Comment by ibecav** [comment]
Works for me! Elegant and lightweight? SMH

Thomas I got your invite you wnat me to go ahead and commit the changes so far?

**Comment by leeper** [comment]
Yes, please merge in your changes and make sure you add yourself as an author in DESCRIPTION.

**Comment by ibecav** [comment]
Merge completed.  It builds successfully and added as author

**Pull request merged**
