### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by ibecav**
Please see also https://github.com/ibecav/CGPfunctions/blob/master/R/newggslopegraph.R and https://github.com/ibecav/CGPfunctions/blob/master/data/newcancer.RData

### CODE REVIEW

**Comment by leeper** [comment]
Rather than a delete and replace, given that people may be using the current function, could I suggest naming this `ggslopegraph2()` and just adding it as a new, separate function?

**Comment by ibecav** [comment]
I'm easy.  I hadn't heard back from anyone other than you for awhile and figured this was the easiest way to let you know I'd done enough work to make it tenable.

**Comment by joranE** [comment]
It's a small thing, but the three argument checks on Times, Measurement and Grouping should really throw an error message more specific than "Times failure". Since you are checking that the name exists as a column in the data frame, maybe say something like "Times variable not found in data frame"? Even better would be to have the variable and data frame object names themselves in the error message.

**Comment by ibecav** [comment]
Thank you, yes, those are just place holders and in the next day or so I intend to flesh them out better.  My question is do you want me to maintain it here or in my own github space.  I also will add some ability to change some of the cosmetics.

**Comment by leeper** [comment]
If you're happy to have it as part of this package, I would say keep editing on this fork/PR and I will merge in. We can also add you as an author on the package (or you can edit DESCRIPTION yourself on your PR).

**Comment by ibecav** [comment]
Okay.  I've corrected the lousy warning messages.  I've added a number of options for user formatting and I have a data set for Tufte's cancer as well as a vignette and doco files. 

Do you want me to change the name to ggslopegraph2?

How best to merge the 4 files into your repository?

**Comment by leeper** [comment]
I would name it `ggslopegraph2()`. Easiest way is just to update this PR or start a new one.

**Comment by leeper** [comment]
Development moved to #26

**Pull request closed without merging**
